### ISSUE TITLE
Overwrites entire records, instead of editing current winner and with just the the region names

### ISSUE THREAD

**Issue by tkoopman** [OddDrifter/region-names-patcher#1]
This seems to ignore the current winning record and instead just creates a whole new record based on default ESM with the Region Name changes. This would just be the same as making sure the original mod is at the end of your load order.

Could you change this to copying the current winner and just edit the fields needed for the Region Names, else I fail to see the benefit over the original mod as still requires either BASH or manual merging of mods when used with other mods that edit these same records like Weather mods. In my case Azurite Weathers and Seasons.

If I am wrong on how this works please let me know I am just basing this on what I am seeing in SSEEdit.

**Comment by OddDrifter** [comment]
> Could you change this to copying the current winner

The patcher already copies the winner. 

> I fail to see the benefit over the original mod as still requires either BASH or manual merging of mods

The benefit to this is supposed to be that you don't need the original Unique Region Names installed or any patches for it. I made the assumption that the patcher would one of the last things you add to a load order, either after a bashed patch or directly before it since that's how I use it. I have the generated patch as the last thing in my load order and if you're not doing the same, then it's probably true that it isn't worth using.

**Comment by tkoopman** [comment]
![Screenshot 2024-09-26 044102](https://github.com/user-attachments/assets/9994054c-7cd7-4dbc-ab61-f82c9c602223)
Are you sure for region records? I use a lot of Synthesis but have separated this one into it's own esp so it can be the only one doing this. Of course this is at the end of my load order.

**Comment by OddDrifter** [comment]
Okay, it seems like I misunderstood your issue. I thought you were talking about cell overrides not regions. This is an oversight on my part. My fault for using vanilla weathers I guess 😭.

**Comment by OddDrifter** [comment]
This should be fixed now.
